name: Docker

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

env:
  IMAGE_NAME: monthgreat-community-server

jobs:
  build-push-to-docker-hub:
    name: Build & Push to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v1
      - uses: crazy-max/ghaction-docker-meta@v2
        id: meta
        with:
          images: |
            tony84727/monthgreat-community-server
          tags: |
            type=raw,value=${{ github.run_number }}
            type=raw,value=latest,enable=${{ github.event_name == 'push' && github.ref == 'refs/heads/master' }}
            type=edge,branch=master
      - name: Log into Docker Hub
        uses: docker/login-action@v1
        with:
          username: tony84727
          password: ${{ secrets.DOCKER_ACCESS_TOKEN }}
      - name: Build and Push
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}